name: Builder

on:
  push:
    branches:
      - master

env:
  CMAKE_VERSION: 3.25.2
  LLVM_VERSION: 15.0.6
  NDK_VERSION: r25b

jobs:
  arm64_only:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Init Linux cross compile env
      run: |
        sh scripts/setup_linux_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: Build Dobby (Linux ARM64)
      run: |
        python3 scripts/platform_builder.py \
          --platform=linux \
          --arch=arm64 \
          --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION \
          --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION
        cp include/dobby.h build/linux
        tar -zcvf build/dobby-linux-arm64.tar.gz build/linux
        cp build/dobby-linux-arm64.tar.gz artifact/
      shell: bash

    - name: Build Dobby (Android ARM64)
      run: |
        python3 scripts/platform_builder.py \
          --platform=android \
          --arch=arm64 \
          --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION \
          --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION \
          --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        cp include/dobby.h build/android
        tar -zcvf build/dobby-android-arm64.tar.gz build/android
        cp build/dobby-android-arm64.tar.gz artifact/
      shell: bash

    - name: List artifacts
      run: |
        echo "=== Artifact files ==="
        ls -lha artifact || true
        ls -lha build || true

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dobby-arm64-artifacts
        path: |
          build/dobby-linux-arm64.tar.gz
          build/dobby-android-arm64.tar.gz
