arm64_only:
    runs-on: ubuntu-latest
    needs: delete_latest_release
    steps:
    - name: checkout master
      uses: actions/checkout@master

    - name: init linux cross compile env
      run: |
        sh scripts/setup_linux_cross_compile.sh
        mkdir -p artifact
      shell: bash

    - name: compile linux (arm64)
      run: |
        # build linux only for arm64 (aarch64)
        python3 scripts/platform_builder.py --platform=linux --arch=arm64 --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION
        cp include/dobby.h build/linux
        tar -zcvf build/dobby-linux-arm64.tar.gz build/linux
        cp build/dobby-linux-arm64.tar.gz artifact/
      shell: bash

    - name: compile android (arm64)
      run: |
        # build android only for arm64 (arm64-v8a)
        python3 scripts/platform_builder.py --platform=android --arch=arm64 --cmake_dir=$HOME/opt/cmake-$CMAKE_VERSION --llvm_dir=$HOME/opt/llvm-$LLVM_VERSION --android_ndk_dir=$HOME/opt/ndk-$NDK_VERSION
        cp include/dobby.h build/android
        tar -zcvf build/dobby-android-arm64.tar.gz build/android
        cp build/dobby-android-arm64.tar.gz artifact/
      shell: bash

    - name: list artifacts
      run: |
        ls -lha artifact || true
        ls -lha build || true
      shell: bash

    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dobby-arm64-artifacts
        path: |
          build/dobby-linux-arm64.tar.gz
          build/dobby-android-arm64.tar.gz
